### ISSUE TITLE
Runtime Patch Possible?

### ISSUE THREAD

**Issue by chico-depressive** [hfiref0x/UPGDSED#1]
Hello hfiref0x

To achieve that I assume kernel is patched and the user needs to reboot, so I have a couple of questions

can you provide a readme.md with more details on how it works?
you have plans to release a tool to disable patchguard in runtime?
It is possible to enable VMX in runtime in windows?(AMD and INTEL)(by changing MSR register)

thank you for releasing this tool, very useful

**Comment by hfiref0x** [comment]
Hello,

all additional info is in Fyyre projects. This one is a just a compilation of them to make it work together on all available versions.

Regarding to "disabling" PatchGuard in runtime.
I very simple explanation why not.

PatchGuard basically is a Microsoft made rootkit which only purpose is to do blue screens by condition. It is a very big piece of junk code inside ntoskrnl that doesn't required for normal Windows work.  What is the simple way to defeat rootkit? Patch in runtime, adopting to each version and risking to screw up somewhere, or do not allow it even start? PatchGuard developers isn't stupid they constantly improve their "software" targetting available in internet "bypasses". So why should we play in their game, if we can invite them to our?

**Comment by chico-depressive** [comment]
nice answer, I do agree with you, it's a shit to develop kernel drivers this days, only because microsoft thinks it can "improve security" by adding useless stuff

I am a big fan of you, want to have your knowledge some day, keep doing great code, thank you
