### ISSUE TITLE
[help] Windows 10 version 1511 x64

### ISSUE THREAD

**Issue by tsm91** [hfiref0x/UPGDSED#13]
Hi, I am having troubles hiding a process on windows 10.  Maybe (most likely, but maybe you can suggest an other utility rootkit which works on win10) this question is totally unrelated and `UPGDSED ` works as expected. I am not familiar with this whole process

Note: I got no issues on win 7 sp1 7601. However I can only install remote desktop protocol version 8.1 on win7. My friend told me on win7 he experience lot slower rdp speed than on win10. This is the reason I want to get it working on win 10. Cause win10 has rdp 10.2 which is lot faster with streaming online games.

I created a Win 10 1511 (TH2) x64 fresh install. Cloned the repo, ran Patch v1.1.3 as an admin. See the log:

```
WARNING: Using this tool might render your PC to an unbootable state.
If you want to continue type CONTINUE (all uppercase) and press Enter

CONTINUE
Patch: Windows Version: 10.0.10586, EFI

Patch: Symbol dlls extracted successfully.
Patch: Dbghelp initialized.
Patch: Copy files to %TEMP%
Patch: Copy success
Patch: Scanning ntoskrnl for patterns

Patch: Ntoskrnl version: 10.0.10586.0

-> SeValidateImageData          003F48C0
-> CcInitializeBcbProfiler      00681094
-> KeInitAmd64SpecificState     006B2EF8
-> ExpLicenseWatchInitWorker    006BB9D0
-> SepInitializeCodeIntegrity   0049C8B8

Patch: Ntoskrnl scan complete
Patch: Scanning winload for patterns

Patch: Winload version: 10.0.10586.0

-> ImgpValidateImageHash        00054A5C

Patch: Winload scan complete

Patch: ModifyFilesAndMove succeed
Patch: Executing BCDEDIT commands
bcdedit.exe -create {71A3C7FC-F751-4982-AEC1-E958357E6813} -d "Patch Guard Disabled" -application OSLOADER
The entry {71a3c7fc-f751-4982-aec1-e958357e6813} was successfully created.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} device partition=C:
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} osdevice partition=C:
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} systemroot \Windows
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} path \Windows\system32\osloader.efi
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} kernel ntkrnlmp.exe
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} recoveryenabled 0
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} nx OptIn
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} nointegritychecks 1
The operation completed successfully.
bcdedit.exe -set {71A3C7FC-F751-4982-AEC1-E958357E6813} inherit {bootloadersettings}
The operation completed successfully.
bcdedit.exe -displayorder {71A3C7FC-F751-4982-AEC1-E958357E6813} -addlast
The operation completed successfully.
bcdedit.exe -timeout 10
The operation completed successfully.
bcdedit.exe -set bootmenupolicy legacy
The operation completed successfully.
Patch: Setting PeAuth service to manual start
Patch: PeAuth service set to manual start

Patch: BcdCreatePatchEntry succeed
Patch: Press Enter to exit
```

All seems to work. Restarted computer, booted into Patch Guard Disabled mode.

![img_20171203_175417](https://user-images.githubusercontent.com/4459551/33527747-e6e74afc-d80a-11e7-84d5-28b91cbac1c9.jpg)

Now, I found a tool called `hidecon`. I think Fyyre created it, specifically for win7 x64. I used it to hide process on win7 by `hidecon -ld; hidecon -ph <PID>`, when I execute `hidecon -ld` on win10 I get:

![hidecon-ld-fail](https://user-images.githubusercontent.com/4459551/33527788-9b8cf7f4-d80b-11e7-8b57-a53a0da33e6b.PNG)

When I press "close" and proceed with `hidecon -ph <PID>` I get BSOD.

Any ideas?

**Comment by hfiref0x** [comment]
Excuse me, what do you want from tool relying on Windows 7 system structures offsets? Work on every OS, developed later in decade? Don't you find it ridiculous to even ask this? This is no how not related to this project and more to say you seems doesn't understand what you do.

**Comment by tsm91** [comment]
Yes i noted this is most likely unrelated. I also pointed out i don't understand what i am doing. 

And yeah, i was arrogant enough to ask for an alternate rootkit which works on win 10 x64. :D

Anyways, sorry about this
