### ISSUE TITLE
Computer freeze randomly

### ISSUE THREAD

**Issue by Whibelf2** [hfiref0x/UPGDSED#17]
I have Windows 10 Version 1709  Build 16299.248

Computer freeze randomly, maybe after 4 hours startup or after 3 days windows started

Windows freeze, mouse freeze, only way to get machine work back is turn off PC on button

Maybe this fault of UPGDSED ?

**Comment by Whibelf2** [comment]
Another issue is, randomly on BCD menu options on startup machine, windows show error:

"Error: Windows failed to start. A recent hardware or software change might have caused the issue"

This occur a few times when I start windows with patchguard disabled.

**Comment by hfiref0x** [comment]
Any use of this software is entirely on your risk. There is no warranties or what so ever. You agreed on that when installed this patch and typed "CONTINUE" in console. Everything above loader work is not a subject of issue here.
