### ISSUE TITLE
[7601_24059] SeValidateImageData -> new_Pattern 

### ISSUE THREAD

**Issue by nonspin** [hfiref0x/UPGDSED#18]
For Windows 7 -> 7601_24059
KB4088875 (Monthly Rollup - March, 18th 2018)

// it's a 'jmp short' now 0xE9->0xEB
0xB8, 0x28, 0x04, 0x00, 0xC0, **0xEB**

ntoskrnl.exe
OFFSET 2C6100 - VA 207F700

	48 83 EC 28          sub rsp,28                   
	33 C0                xor eax,eax                  
	38 05 6C 13 ED FF    cmp byte ptr ds:[1F50A78],al 
	74 16                je 207F724 <- (1)                  
	4C 8B 0D 53 13 ED FF mov r9,qword ptr ds:[1F50A68]
	4C 3B C8             cmp r9,rax                   
	75 07                jne 207F721                  
	B8 28 04 00 C0       mov eax,C0000428 <- (2)           
	EB 03                jmp 207F724                  
	41 FF D1             call r9
	//  VA  207F724                   
	48 83 C4 28          add rsp,28                 
	C3                   ret

```
(1)
This version cleaned up all sub-routines,
it actually looks tidy :)
I suggest patching (1) 'je->jmp' because EAX is 0
at this point and a jmp would do just fine. 

.. Unless you implement nibble_level search,
you have to add a new pattern starting with this version
anyway.

// tested the above and works fine w7x64
```

```
(2)
Old location
```

**Comment by hfiref0x** [comment]
Hello,

which one KB installs this kernel? I'm sorry I don't have any Windows 7 to check.

**Comment by nonspin** [comment]
Line 2? "KB4088875 (Monthly Rollup - March, 18th 2018)"?
http://www.catalog.update.microsoft.com/Search.aspx?q=KB4088875

**Comment by hfiref0x** [comment]
Ok thanks.

**Comment by hfiref0x** [comment]
Well, even corrected this signature now is in conflict with **SeValidateImageHeader**. So more workaround required. Good news, nothing else is affected after this patch in  ntoskrnl.exe and winload.exe(efi).

**Comment by hfiref0x** [comment]
See commit dfb48931bbeb318219a3c8bed9d51417f80d4739, as you suggested for Windows 7 conditional jump was patched.

**Comment by nonspin** [comment]
I might be wrong, but while it does work for Windows 7 (7601_24059 - KB4088875),
it doesn't work for any other (prior) kernels of Windows 7 ?

**Comment by hfiref0x** [comment]
So far I tried 6.1.7601.18471, 6.1.7601.23418, 6.1.7601.24059 and this looks same everywhere. Maybe this Melthdown/Spectre patches also changed something in different Windows versions like for example 8.1 but I don't have their recent kernels to check this out. Anyway search of **SeValidateImageData** is much more trivial in Win8.1+ as it is more simple signature (mov eax, STATUS_INVALID_IMAGE_HASH).

**Comment by nonspin** [comment]
Never realized that my solution was backwards compatible.
I didn't even think of checking, because of the FAR Jmp from the old pattern ... 
Nevermind, lol

**Comment by hfiref0x** [comment]
The more simplest way is to set eax to 0 and write ret directly in the beginning of this function. This will make code simple.

**Comment by hfiref0x** [comment]
Pushed at master as v 1.2.1
