### ISSUE TITLE
[minor] bcd.c -> static "Windows"

### ISSUE THREAD

**Issue by nonspin** [hfiref0x/UPGDSED#21]
*src/bcd.c*

	Ln:555
	_strcat(szCommand, TEXT(" systemroot \\Windows"));

	Ln:570
	_strcat(szCommand, TEXT(" path \\Windows\\system32\\"));

It is assumed, that Windows is located in the "Windows"-Folder.
If it isn't (Customized/Personalized or WhateverReason),
it'll fail (invalid path).

consider:
	%windir% or %systemroot%
	-> Trim %systemdrive%

**Comment by hfiref0x** [comment]
Changing default os directory path requires pre-installation setup tweaks or a lot of work after install (I doubt it will fully working or bootable). If user installed OS in non default environment it is not a our problem - if he was smart enough for this then he will be smart enough to recompile this tool and make path changes himself.

**Comment by nonspin** [comment]
yeah i know, just wanted to point it out in case you get bored ..
you may close it..
