### ISSUE TITLE
Unsupported Windows Version: 10.0.17686

### ISSUE THREAD

**Issue by Klimosity** [hfiref0x/UPGDSED#28]
Can you make a 'riskier' version which supports all Windows 10 builds, but at your own risk. I would love to use this but run the Insider loop.

**Comment by hfiref0x** [comment]
Insider builds are not supported and won't be. It is a waste of time.

**Comment by Fyyre** [comment]
F0x already answered... but to clarify.... We both hate Windows 10, with a burning passion.  Insider builds would be ultra time waster.
