### ISSUE TITLE
Support ARM64 versions of Windows

### ISSUE THREAD

**Issue by Googulator** [hfiref0x/UPGDSED#29]
Windows 10 has been ported to ARM64, and there are now devices shipping with it (e.g. Asus TP370QL).

Unfortunately ARM64 is encumbered with the same PatchGuard rules as X64. Support is therefore needed for disabling PatchGuard on ARM64.

**Comment by hfiref0x** [comment]
I'm sorry, no plans for ARM64 at least from us.
