### ISSUE TITLE
Not Working on Windows 10 Build 1709

### ISSUE THREAD

**Issue by adeelmunir** [hfiref0x/UPGDSED#30]
Hi Fyyre,

I am using your tool to disable patch guard on windows 10 build version 1709, after running the tool, I checked bcdedit and it is updated with patch guard disable and booted my PC using disable patchguard boot option, it seems that all is good, so to confirm it further I used https://gist.github.com/andronoob/d5882c5e6d21f3dea534a68434abe040 andronoob NTFS FSD hook filter and starting this service using following tool:

sc create FsFilter binPath= C:\temp\FsFilter1.sys type= kernel
sc start FsFilter
But I am getting blue screen and windows crashing, means patch guard is not disabled.

Can you please help me, what I am doing wrong? your quick response will be highly appreciated.

Thanks

BR,
Adeel

**Comment by mrexodia** [comment]
I tested with TitanHide and everything is working fine for me.

**Comment by adeelmunir** [comment]
Hi Mrexodia,

Did you test it on Win10? if yes then which buid version, also could you please share .sys and inf files of TitanHide for windows 10?

How much time you ran the TintanHide to confirm patchguard ?


Thanks

**Comment by mrexodia** [comment]
Why would I post on an issue about win 10 1709 if I didn’t test there?

You can compile TitanHide yourself. As far as I know the vm is still running, but I’ll check in a moment.

**Comment by mrexodia** [comment]
Ah, the vm just bsod so it's not working...

**Comment by adeelmunir** [comment]
So you are sure that with patchguard diable boot option on windows 10, you got BSOD, that means patchguard disable tool didnot work? right

**Comment by mrexodia** [comment]
Yes that is correct.

**Comment by adeelmunir** [comment]
Hi Fyyre,

could you please help us?


Thanks

**Comment by nonspin** [comment]
Just to get the obvious out of the way, ..
.. FsFilter.sys is "FileSystem"-related, right ?
Maybe it's not meant to run in a VM and therefore not caused
by UPGDSED ?!

**Comment by mrexodia** [comment]
You should read the comments once more to not state the obvious:)

**Comment by nonspin** [comment]
Thing is, i didn't state anything .. i did two of them 'question-things' .. obviously ;D

**Comment by hfiref0x** [comment]
It is not unexpected. There was no guarantee that fast changing Windows 10 won't give any surprises. You should wait for @Fyyre reply, (as this project is entirely based on Fyyre researches). Or you can figure out patchguard changes on your own. Keep it mind that it possible to implement patchguard in a way which will render file patching useless, as system simple won't be able to boot without this piece of properly initialized DRM junk.

**Comment by Fyyre** [comment]
I admit to having lost much interesting in this project.  I am seeing it used by people mainly to cheat in online games, and credit is never correctly given to myself or hFiref0x for the work.

**Comment by Whibelf2** [comment]
> I admit to having lost much interesting in this project. I am seeing it used by people mainly to cheat in online games, and credit is never correctly given to myself or hFiref0x for the work.

Hi Fyyre please not stop update this project, is very useful for me, for malware analysis

I'm grateful, please not stop, this project is incredible !

**Comment by hfiref0x** [comment]
Additionally to Fyyre words, you are free to fork, reverse fresh windows and pull request (optionally) with fixes/support whatever. We are not going to support this "forever". Closed.
