### ISSUE TITLE
IF %TEMP% is set to a different drive ..

### ISSUE THREAD

**Issue by nonspin** [hfiref0x/UPGDSED#5]
... error "System cannot move files to a different drive" when trying to find pattern
in winload - (ntoskrnl portion completes w/no fail)

ex.: If system is "C:\Windows\" and %TEMP% is "D:\Temp\" it will fail.

**Comment by hfiref0x** [comment]
Should be fixed now. We completely forgot about MoveFileEx behavior in this particular case.
