### ISSUE TITLE
[NotABug] bcd identifier -> removal

### ISSUE THREAD

**Issue by nonspin** [hfiref0x/UPGDSED#6]
Since the GUID (bcd_identifier) is unique to each system, maybe either:
- add it to the BcdPatchEntryAlreadyExist Output
  -> "removal: "bcdedit /delete " + bcd_identifier
or
- add command-line option "-remove"

**Comment by hfiref0x** [comment]
GUID used by this program is constant, see bcd.h. Idea of adding it to the output if entry already exist looks fine for me.

**Comment by nonspin** [comment]
Since the following is bcd-related i'll skip creating new issues..

Is there a reason why "-set {bootmgr} nointegritychecks 1" is skipped now?
If yes. shouldn't it check for it and - if present and 1 - remove it, because older
solutions created it ?

Assuming, my bootmenu has multiple entries for multiple OS on multiple partitions,
a static GUID (bcd ident) limits it to a single use.. What's the thought behind it?
Suggestion: 
Using "bcdedit -copy"  on {current} if "kernel ntkrnlmp.exe" is not set.
-> and then maybe adding " | pg:off |" to the desc. to have a reference.

**Comment by hfiref0x** [comment]
Not a bug however. Fyyre reported that this setting was causing Bitlocker (if system volume encrypted) ask for key uppon reboot.

**Comment by hfiref0x** [comment]
Patch will now output removal instruction for BCD entry in case if patch entry already exist.
